package astava.java;

public class ASTType {
    public static final int CLASS = 0;
    public static final int METHOD = 1;
    public static final int RETURN_VALUE_STATEMENT = 2;
    public static final int BOOLEAN_LITERAL = 3;
    public static final int BYTE_LITERAL = 4;
    public static final int SHORT_LITERAL = 5;
    public static final int INT_LITERAL = 6;
    public static final int LONG_LITERAL = 7;
    public static final int FLOAT_LITERAL = 8;
    public static final int DOUBLE_LITERAL = 9;
    public static final int CHAR_LITERAL = 10;
    public static final int STRING_LITERAL = 11;
    public static final int REDUCE = 12;
    public static final int BLOCK = 13;
    public static final int VARIABLE_DECLARATION = 14;
    public static final int VARIABLE_ASSIGNMENT = 15;
    public static final int VARIABLE_ACCESS = 16;
    public static final int INCREMENT = 17;
    public static final int NOT = 18;
    public static final int COMPARE = 19;
    public static final int SHIFT = 20;
    public static final int BITWISE = 21;
    public static final int LOGICAL = 22;
    public static final int IF_ELSE = 23;
    public static final int BREAK_CASE = 25;
    public static final int CONTINUE = 26;
    public static final int INSTANCE_OF = 27;
    public static final int INVOCATION = 28;
    public static final int NEW_INSTANCE = 29;
    public static final int RETURN_STATEMENT = 30;
    public static final int LABEL_SCOPE = 31;
    public static final int LABEL_SET = 32;
    public static final int LABEL_GO_TO = 33;
    public static final int LABEL = 34;
    public static final int GO_TO = 35;
    public static final int SWITCH = 36;
    public static final int CASE = 37;
}
